#!/bin/bash -e
echo running depmod
depmod

action="$1"
oldversion="$2"

if [ "$action" != configure ]; then
    exit 0
fi

stowaway=""
boot=""
cmdline=$(</proc/cmdline)

echo Kernel images installed to /usr/share/kernel/

if [[ "$cmdline" =~ ^(.*)bootpartition\=([a-z0-9]*)(.*)$ ]];
then
  boot="${BASH_REMATCH[2]}"
fi

if [[ "$cmdline" =~ ^(.*)stowaways_os\=([a-z0-9]*)(.*)$ ]];
then
  stowaway="${BASH_REMATCH[2]}"
fi

if [ -n "$boot" ]
then
  echo "You need to write the correct kernel to the correct boot partition based upon your boot configuration:"
  if [ -n "$stowaway" ]
  then
    echo "sudo dd if=/usr/share/kernel/linux-boot-stowaways-debian.img of=/dev/disk/by-partlabel/${boot}"
  else
    echo "sudo dd if=/usr/share/kernel/linux-boot.img of=/dev/disk/by-partlabel/${boot}"
  fi
else
  echo "You need to write the correct kernel to the correct boot partition based upon your boot configuration."
  echo "eg: sudo dd if=/usr/share/kernel/linux-boot.img of=/dev/disk/by-partlabel/boot2"
  if [ -n "$stowaway" ]
  then
    echo "or: sudo dd if=/usr/share/kernel/linux-boot-stowaways-${stowaway}.img of=/dev/disk/by-partlabel/boot3"
  else
    echo "or: sudo dd if=/usr/share/kernel/linux-boot-stowaways-debian.img of=/dev/disk/by-partlabel/boot3"
  fi
fi
