#!/bin/sh -e

action="$1"
oldversion="$2"

if [ "$action" != configure ]; then
    exit 0
fi

echo Kernel installed to /usr/share/kernel/linux-boot.img
echo You need to write it to the correct boot partition based upon your boot configuration.
echo eg: sudo dd if=/usr/share/kernel/linux-boot.img of=/dev/disk/by-partlabel/boot2
echo or: sudo dd if=/usr/share/kernel/linux-boot-stowaways-debian.img of=/dev/disk/by-partlabel/boot3
